[package]
name = "bevy-ws-server"
version = "0.2.1"
edition = "2021"

[dependencies]
bevy = { version = "0.15", default-features = false, features = ["multi_threaded"] }
async-net = "2"
futures = "0.3"
async-tungstenite = "0.29"
log = "0.4"
crossbeam-channel = "0.5"
async-channel = "2"
